# install `pre-commit` first.
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: ['--line-length=79']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
      args: ['--ignore=E203,E402,E731,W50']
    - id: pretty-format-json
      args: ['--autofix', '--no-sort-keys']
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: ['--fix=auto']